export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';